[core]
log_file = "stderr"
log_mode = "prod"
max_cpus = "32"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "stderr"
tls_enabled = true
tls_cert = "/etc/gridsecurity/host.cert"
tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["storage_provider_svc", "auth_svc", "storage_broker_svc"]

[http]
enabled_services = ["prometheus_svc", "webui_svc", "ocdav_svc"]
network = "tcp"
address = "0.0.0.0:9998"

[grpc.storage_provider_svc]
driver = "local"
mount_path = "/local"
mount_id = "123e4567-e89b-12d3-a456-426655440000"

[grpc.auth_svc.auth_manager]
driver = "demo"

[grpc.auth_svc.token_manager]
driver = "jwt"

[grpc.auth_svc.user_manager]
driver = "demo"

[grpc.storage_provider_svc.eos]
mgm = "root://nowhere.org"
root_uid = 0
root_gid = 0

[grpc.storage_provider_svc.local]
root = "/tmp"

[grpc.storage_broker_svc]
driver = "static"

[grpc.storage_broker_svc.static.rules]
"/local" = "localhost:9999"
"123e4567-e89b-12d3-a456-426655440000" = "localhost:9999"

[http.prometheus_svc]
prefix = "metrics"

[http.webui_svc]
prefix = "ui"

[http.ocdav_svc]
prefix = "webdav"
storageprovidersvc = "localhost:9999"
